#!/usr/bin/env python3
import sys

from utils._utils import SEPARATOR, getBasePathName, runSystemFittedProcess, throwError
from utils.aws_utils import createPullRequestCommand
from utils.cli_utils import customInput
from utils.git_utils import getCurrentGitBranchName, getLatestCommitMessage
from utils.repo_utils import runTests

if __name__ == "__main__":
    if len(sys.argv) > 2:
        throwError('Incorrect Usage.\nTry: python3 pr target')


    # runTests()

    # Get the current branch name and latest commit message
    current_branch = getCurrentGitBranchName()
    latest_commit_message = getLatestCommitMessage().split("\n")[0]
    base_path = getBasePathName()
    default_title = f"{current_branch.upper()}: {latest_commit_message}"

    if len(sys.argv) == 2:
        # DEFAULTS
        if sys.argv[1] == '--d':
            target = "development"
            repository = base_path
            title = default_title
            desc = ""
        else:
            throwError(f'{sys.argv[1]} not a valid command')
    else :
        target = customInput("Where is your destination?", "development")
        repository = customInput("What is the name of the repository?", base_path)
        title = customInput("What is your PR named?", default_title)
        desc = customInput("What is the description of your PR (optional)?", "")

    repository = repository.replace(" ", SEPARATOR)
    target = target.replace(" ", SEPARATOR)
    title = title.replace(" ", SEPARATOR)
    desc = desc.replace(" ", SEPARATOR)

    runSystemFittedProcess(createPullRequestCommand(target, repository, title, desc))
