name: Build and Release Fusion, a Python CLI Tool

on:
  push:
    tags:
      - "release_*"

permissions:
  contents: write  # Needed to create a GitHub release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      # macOS build
      - name: Build for macOS
        if: runner.os == 'macOS'
        run: |
          pyinstaller --onefile fusion.py
          mkdir dist-${{ matrix.os }}
          mv dist/fusion* dist-${{ matrix.os }}/fusion
          chmod +x dist-${{ matrix.os }}/fusion

      # Windows build
      - name: Build for Windows
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile fusion.py
          mkdir dist-${{ matrix.os }}
          move dist\\fusion.exe dist-${{ matrix.os }}\\fusion.exe

      # Linux build
      - name: Build for Linux
        if: runner.os == 'Linux'
        run: |
          pyinstaller --onefile fusion.py
          mkdir dist-${{ matrix.os }}
          mv dist/fusion* dist-${{ matrix.os }}/fusion
          chmod +x dist-${{ matrix.os }}/fusion

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fusion-${{ matrix.os }}
          path: dist-${{ matrix.os }}/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
