name: Build and Release Fusion CLI Tool with Installers

on:
  push:
    tags:
      - "release_*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      # Install fpm and other dependencies for Linux
      - name: Install fpm (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install ruby-full
          gem install --user-install fpm

      # macOS installer
      - name: Create macOS .pkg installer
        if: runner.os == 'macOS'
        run: |
          pyinstaller --onefile fusion.py
          mkdir dist-macos
          mv dist/fusion dist-macos/fusion

          # Create a directory for packaging
          mkdir -p /tmp/fusion-package/usr/local/bin
          cp dist-macos/fusion /tmp/fusion-package/usr/local/bin/

          # Use pkgbuild to create the .pkg installer
          pkgbuild --identifier com.example.fusion --version 1.0 --install-location /usr/local/bin --root /tmp/fusion-package dist-macos/fusion.pkg

      # Windows installer
      - name: Create Windows .exe installer
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile fusion.py
          mkdir dist-windows
          mv dist\\fusion.exe dist-windows\\fusion.exe
          # Use Inno Setup or NSIS to create the installer
          inno-compiler /INPUT=installer_script.iss /OUTPUT=dist-windows/fusion-installer.exe

      # Linux installer (Debian-based)
      - name: Create Linux .deb installer
        if: runner.os == 'Linux'
        run: |
          pyinstaller --onefile fusion.py
          mkdir dist-linux
          mv dist/fusion dist-linux/fusion
          fpm -s dir -t deb -n fusion -v 1.0 --prefix /usr/local/bin dist-linux/fusion

      - name: Upload installer artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fusion-installers
          path: |
            dist-macos/*.pkg
            dist-windows/*.exe
            dist-linux/*.deb

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all installer artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
