name: Build and Release Fusion CLI Tool with Installers

on:
  push:
    tags:
      - "release_*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      # macOS installer
      - name: Create macOS .pkg installer
        if: runner.os == 'macOS'
        run: |
          pyinstaller --onefile fusion.py
          mkdir dist-macos
          mv dist/fusion dist-macos/fusion

          # Create a directory for packaging
          mkdir -p /tmp/fusion-package/usr/local/bin
          cp dist-macos/fusion /tmp/fusion-package/usr/local/bin/

          # Use pkgbuild to create the .pkg installer
          pkgbuild --identifier com.example.fusion --version 1.0 --install-location / --root /tmp/fusion-package dist-macos/fusion.pkg

      # Windows installer
      - name: Install Inno Setup (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install innosetup -y
          # Ensure the path is updated for innoisetup
          $env:PATH = "$env:PATH;C:\Program Files (x86)\Inno Setup 6"

      - name: Create Windows .exe installer
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile fusion.py
          mkdir dist-windows
          mv dist\\fusion.exe dist-windows\\fusion.exe
          
          # Use Inno Setup to create the installer
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer_script.iss
          mv fusion-installer.exe dist-windows\\fusion-installer.exe

      - name: Upload installer artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fusion-installers-${{ matrix.os }}
          path: |
            dist-macos/*.pkg
            dist-windows/fusion-installer.exe  # Only upload the installer exe, not the raw fusion.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all installer artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
