name: Build Python CLI Tool

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your dependencies

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build the application
      run: |
        pyinstaller --onefile cli.py  # Change to your script name if needed

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: python-cli-binaries
        path: dist/*
